---
title: Terms and Conditions
published: true
tag: 
 - Terms and Conditions
 - Legal
 - Obligations
---

# Terms & Conditions
**Last Updated: 27 August 2024**

## Overview
Alexander Jonathan Hardy Steffen, Barrister and Solicitor ("Hardy Steffen," "we," "us," "our") owns and operates the Hardy Steffen shopping networks, network of websites including ajhs.li, hardysteffen.com and others, mobile applications, and any other linked and related pages, content, features, products, software, and tools offered by Hardy Steffen (the "Services"). From time to time, Hardy Steffen may restrict access to some parts of the Website, or the entire Website, to visitors and users, including registered users of the Hardy Steffen Service.

**PLEASE READ THESE TERMS OF USE CAREFULLY.** BY ACCESSING OR USING THIS WEBSITE OR ANY OTHER WEBSITES (WHETHER OPERATED BY HARDY STEFFEN OR ANY THIRD PARTY), AS WELL AS ALL CONTENT, SERVICES, INFORMATION, AND ANY PORTIONS THEREOF (COLLECTIVELY, THE "SITE") MADE AVAILABLE BY THIS WEBSITE, ITS AFFILIATES, OR ITS AGENTS IN ANY WAY, INCLUDING USING THE SERVICE AND/OR OTHER RESOURCES AVAILABLE OR ENABLED VIA THE SITE, OR COMPLETING ANY REGISTRATION PROCESS, AND/OR BROWSING THE SITE, YOU REPRESENT THAT:

1. YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THESE TERMS OF USE, AND 
2. YOU ARE OF LEGAL AGE TO FORM A BINDING CONTRACT WITH HARDY STEFFEN. 

IF YOU DO NOT AGREE TO THESE TERMS YOU ARE NOT AUTHORIZED TO AND YOU MAY NOT USE THE SITE. THE TERM "YOU" REFERS TO THE INDIVIDUAL OR LEGAL ENTITY, AS APPLICABLE, IDENTIFIED AS THE USER WHEN YOU USE OR REGISTER ON THE SITE.

Any new features or tools which are added to the current store shall also be subject to the Terms of Service. You can review the most current version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website following the posting of any changes constitutes acceptance of those changes.

## Use of Services
You must be 18 years or older to use our Services. This Agreement is void where prohibited by law, and the right to access and use the Services is revoked in such jurisdictions.

By accessing the Services, you represent and warrant to Hardy Steffen that:
1. You are an individual (i.e., not a corporation) at least 18 years old;
2. You are of legal age to form a binding contract;
3. All registration information you submit is accurate and truthful and you will maintain the accuracy of such information;
4. You are legally permitted to use and access the Services and take full responsibility for your access, selection and use of the Services.

## User Submissions
In the course of using the Services, you and other users may provide content or information which may be used by Hardy Steffen in connection with the Services and which may be visible to certain other users. By posting information, images, video, blogs, or other content on the Services (collectively, "User Submissions") or otherwise providing User Submissions to Hardy Steffen in connection with the Services, you hereby grant to:

1. Hardy Steffen an exclusive, worldwide, royalty free, perpetual, irrevocable, sublicensable, transferable right to fully exploit (including without limitation, reformatting, modifying, creating derivative works of, and translate) such User Submissions (including all related intellectual property rights) in connection with the Services and Hardy Steffen (its successors' and assigns') business, including without limitation for promoting and redistributing part or all of the Services (or any derivative works thereof) in any media formats and through any media channels, and to allow others to do so; and
2. Each user of the Services a non-exclusive license to access your User Submissions through the Services, and to use, modify, reproduce, distribute, prepare derivative works of, display, and perform such User Submissions as permitted through the functionality of the Services under this Agreement.

You understand that all information publicly posted or privately transmitted through the Services is the sole responsibility of the person from which such content originated and that Hardy Steffen will not be liable for any errors or omissions in any such content.

## Content
### Copyrights
All materials displayed or performed on the Services, including, but not limited to text, blogs, graphics, articles, photographs, images, illustrations video, and User Submissions (also known as the "Content"), are protected by copyright.

You shall abide by all copyright notices, trademark rules, information, and restrictions contained in any Content accessed through the Services, and shall not use, copy reproduce, modify translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purposes whatsoever any Content or other proprietary rights not owned by you, (i) without the express prior written consent of Hardy Steffen or the respective owners, and (ii) in any way that violates any third party right. The Services are protected by copyright as collective works and/or compilations, pursuant to Canadian and U.S. copyright laws, international conventions, and other intellectual property laws.

**You may not modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Agreement), create derivative works based on, distribute, perform, display, or in any way exploit, any of the Content, software, materials, or Services in whole or in part.**

### Intellectual Property
The technology and the software underlying our Services is the exclusive property of Hardy Steffen. Subject to your compliance with this Agreement, Hardy Steffen grants you a limited, non-exclusive, non-transferable, non-sub-licensable, revocable license to access and make personal and non-commercial use of the Services, and any software underlying our Services solely to use the Services, as provided by Hardy Steffen in accordance with this Agreement.

This license does not include any resale or commercial use of any Services or any Content. You shall not copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying our Services. You agree not to use modified versions of any software underlying our Service, including without limitation, for the purpose of obtaining unauthorized access to our sites or applications. You may not use any of our Services for any illegal purpose.

All rights in the product names, company names, trade names, logos, service marks, trade dress, slogans, product packaging, and designs of Hardy Steffen, its affiliates, or third-party products or services, whether or not appearing with a trademark symbol, belong exclusively to Hardy Steffen or their respective owners, and are protected from reproduction, imitation, dilution, or confusing or misleading uses under national and international trademark and copyright laws. You are prohibited from bidding on keywords containing "Hardy Steffen" or other similar words or marks, including, but not limited to, misspellings thereof, for the purpose of driving traffic to your pages. The use or misuse of these trademarks or any materials containing the trademarks, except as permitted herein, is expressly prohibited, and nothing stated or implied on the Services confers on you any license or right under any patent or trademark of Hardy Steffen, its affiliates, or any third party.

**All rights not expressly granted under this Agreement are reserved by Hardy Steffen and/or its licensors.**

## Restrictions and other Prohibited Activities
You agree that you will not, and will not permit others to:
1. Damage, interfere with or unreasonably overload the Services;
2. Introduce any code intended to disrupt the Services;
3. Alter or delete any information, data, text, links, images, software, chat, communications and other Content of the Services;
4. Access the Services by expert system, electronic agent, "bot" or other automated means;
5. Use scripts or disguised redirects to derive financial benefit from Hardy Steffen;
6. Use the manual or automated software, devices, or other processes to "crawl" or "spider" or index any page or Content of the Services;
7. Modify, reverse engineer, reverse assemble, decompile, copy or otherwise derive the source code of the Services;
8. Rent, sell or sublicense any of the Services;
9. Provide any unauthorized third party with access to the Services;
10. Access or attempt to access confidential information through the Services;
11. Interfere with the operation of the Services, including, but not limited to, distribution of unsolicited advertising or mail messages and propagation of computer worms and viruses;
12. Use the Services to violate the security of any computer network, crack passwords or security encryption codes, transfer or store illegal material including that are deemed threatening or obscene.

Any violation of this Agreement, including, but not limited to the above may be grounds for termination of your right to access or use the Services. Hardy Steffen reserves the right to take appropriate legal action.

## Warranties and Privacy
Without limiting the generality of the foregoing, Hardy Steffen makes no representations or warranties regarding the accuracy of descriptions displayed anywhere on the Services, or regarding suggestions or recommendations of services or products offered or purchased through the Service.

For information regarding Hardy Steffen's treatment of personal information, please review our current Privacy Statement.

## Limitation of Liability
You agree to indemnify, defend, and hold Hardy Steffen and its parents, subsidiaries, affiliates, officers and employees, harmless from any claim or demand (including, without limitation, from all damages, liabilities, settlements, costs and attorneys' fees) made by any third party due to or arising out of your access to or use of the Services, the violation of this Agreement by you, or the infringement by you, or any third party using your account, of any intellectual property or other right of any person or entity.

You agree to cooperate fully as reasonably required in defense and/or settlement of any claim. We reserve the right, in our sole discretion, to assume exclusive control over the defense and/or settlement of any matter subject to indemnification by you.

## Errors and Omissions
Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order).

We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated.

## Third Parties
The Services may contain links to third party websites that are not owned or controlled by Hardy Steffen, or that may be accessible by logging in through a third party website, as described more fully in our Privacy Policy. You hereby represent and warrant that you have read and agree to be bound by all applicable policies of any third party website relating to your use of the Services and that you will act in accordance with those policies, in addition to your obligations under this Agreement.

Hardy Steffen has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of, or opinions expressed in any third party websites. In addition, Hardy Steffen will not and cannot monitor, verify, censor or edit the content of any third party site.

By using the Services, you expressly relieve and hold harmless Hardy Steffen from any and all liability arising from your use of any third party website.

You agree that Hardy Steffen shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. If there is a dispute between participants on this site, or between users and any third party, you understand and agree that Hardy Steffen is under no obligation to become involved.

## Modification and Termination
The validity, construction, and interpretation of this Agreement, and the rights and duties of the parties hereto, will be governed by and construed in accordance with the laws of the Province of Ontario in Canada excluding its conflicts of laws principles. However, the agreement to arbitrate in the following paragraph is governed by Canadian federal law.

## No Assignment
This Agreement is not assignable, transferable or sublicensable by you except with Hardy Steffen's prior written consent. Hardy Steffen may transfer, assign or delegate this Agreement and its rights and obligations without consent.

## Entire Agreement
You and Hardy Steffen agree that this Agreement (including any terms or policies expressly incorporated herein) is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement, and that all modifications must be in a writing signed by both parties, except as otherwise provided herein.
